language: ruby
rvm:
  - "2.2"
  - "2.3"
  - "2.4"
env:
  - INCLUDE_LINGUIST=true
  - INCLUDE_LINGUIST=false

before_install:
  - gem install bundler -v '1.17.3'
  - if [[ "$INCLUDE_LINGUIST" == "true" ]]; then BUNDLE_GEMFILE=Gemfile.optional; sudo apt-get install libicu-dev -y; fi
